### ISSUE TITLE
Latest Discryptor build causes the Windows 10 OS to freeze during boot after the install

### ISSUE THREAD

**Issue by konishiki** [DavidXanatos/DiskCryptor#10]
Hi,
The current Diskcryptor release has prevented OS booting on the latest Windows 10 build after the install and during the restart. OS freezes before making it to the login screen.

Installed on a Dell XPS15 and XPS13 with the same result. I could recover one laptop through booting into a tool called Strelec an editing the registry to remove the affected entry. This problem also occurred with the original version prior to this project revisiting the development.

**Comment by mundavian** [comment]
Exact same issue with Lenovo P620 workstation with Ryzen processor, Win 10 Pro.  After DiskCryptor exe install, reboot produces BSOD before login.  Only remedy is restore point/registry edit.   No one else experiencing this?

**Comment by DavidXanatos** [comment]
Try disabling secure boot, i think the sertificate used for the driver is only accepted on non secure boot systems.
or set some reg key to make your windows think it was upgraded from an older version 16xx that it also accepts the cert

**Comment by mundavian** [comment]
Disabled secure boot and it came right up.  Thank you sir!
