### ISSUE TITLE
bluescreen 

### ISSUE THREAD

**Issue by hardbelit** [DavidXanatos/DiskCryptor#104]
running without any problems for 4 years , after a simple restart, I got bluescreen: 

![20240623_162945](https://github.com/DavidXanatos/DiskCryptor/assets/173626970/1c5f5816-6d3a-464d-a527-995789aacc75)

![2](https://github.com/DavidXanatos/DiskCryptor/assets/173626970/6731d28f-512e-4875-b123-18c16cd52824)

![1](https://github.com/DavidXanatos/DiskCryptor/assets/173626970/c70b0a64-2c56-41e7-b9ce-97c2c5082775)

is there any hope to can recover the files  and what i keep in this hard ?

any good suggestion is welcome

**Comment by hardbelit** [comment]
I don't know if it would be advisable for the hard  to decipher the E :\ partition

**Comment by hardbelit** [comment]
after restart , i add the pwd and windows show the : stop code ntfs file system.
this enter in restart , and try to recovery , but didnt recovery,

**Comment by hardbelit** [comment]
the hard Adata Legent 710 is nvme was is with windows 10  on a second computer

**Comment by DavidXanatos** [comment]
Well same thing you need to recover the files and you can try to recover the volume itself, windows repair never works as it lacks the DC driver mounting it on a different system, or running from a live windows is already the right approach.

**Comment by hardbelit** [comment]
so after i backup the Headers , i will try to decrypt., maybe i see the files

**Comment by hardbelit** [comment]
what you can recommend for point : 2a:

**Comment by DavidXanatos** [comment]
I would try chkdsk e: /F on the encrypted volume

**Comment by DavidXanatos** [comment]
2a: WinHex can do disk images

**Comment by hardbelit** [comment]
chkdsk E: /F 
sfc /scannow /offbootdir=E:\  /offwindir=E:\windows


![image](https://github.com/DavidXanatos/DiskCryptor/assets/173626970/3cdfef29-e047-4996-9839-7d1e0ed76373)

![image](https://github.com/DavidXanatos/DiskCryptor/assets/173626970/8894f1b8-3289-4759-8f5c-3c8d42c337d6)

![image](https://github.com/DavidXanatos/DiskCryptor/assets/173626970/d4409751-44cd-4280-b072-87aa59bdc158)

I will try to see if work, on boot.

thank you

**Comment by DavidXanatos** [comment]
I'm glad I could help :)

**Comment by hardbelit** [comment]
Thank you a lot
