### ISSUE TITLE
update 3 months ago

### ISSUE THREAD

**Issue by liskaaaaaaaaaa** [DavidXanatos/DiskCryptor#11]
last update 3 months ago. when new update  ?

**Comment by DavidXanatos** [comment]
Probably in a few weeks,
I'm very busy with my other projects currently.
And well its working there isn't much to improve,

I could create a new Qt Based UI but that would just make the package 20MB larger for not much benefit.

On the long therm I'm looking into adding a container encryption feature of some sort but that's all far from even started yet.

**Comment by liskaaaaaaaaaa** [comment]
@DavidXanatos  
Hi again ,
Could you please send me Beta 4 for test ?

I'm your fan

**Comment by dabugen** [comment]
Thanks for giving this project a new life, been using it since years. Just wondering if you are still at it and if there will be new updates in 2021?

**Comment by DavidXanatos** [comment]
I'm very busy with sansboxie these days, but yes I have not forgotten DiskCryptor and yes there will be updates this year.
