### ISSUE TITLE
If I use the entire volume mounted without encrypting it, will the data stored be encrypted?

### ISSUE THREAD

**Issue by Sayat1** [DavidXanatos/DiskCryptor#116]
I didn't feel the need to encrypt the entire volume because the disk is initialized to 0, and I'm using it mounted with a pause during encryption,

My question is, if I pause during encrypt and use it while mounted, will the subsequent data be stored encrypted?

**Comment by DavidXanatos** [comment]
The data to the ofset where it was encrypted will be encrypted and the data past that offset will remain unencrypted.
if you stop at next to 0 than next to nothing will be encrypted no mater when its saved.

I would recommend to schrink the volume first in wondows disk management then encrypt only whats realy there and then after encryption finished expand the volume agian this way you will avoid encrypting the empty space.

**Comment by Sayat1** [comment]
Thank you for your quick and detailed answer.
