### ISSUE TITLE
Compilation instructions

### ISSUE THREAD

**Issue by yomon598** [DavidXanatos/DiskCryptor#18]
Hello! It seems the project makes use of EDK and that takes some setting up, so would it be possible to get more detailed environment setup and compilation instructions?
Thanks!

**Comment by DavidXanatos** [comment]
Just refer to the Verycrtypt-DCS documentation

**Comment by yomon598** [comment]
Will do, but that seems to be quite out of date as well.

**Comment by DavidXanatos** [comment]
Well out of date is relative for me it worked and i don't see a reason why it would stop working and yea i did not use the latest VS just the one that was indicated
