### ISSUE TITLE
Win10 Repair after system drive encryption

### ISSUE THREAD

**Issue by mydani** [DavidXanatos/DiskCryptor#22]
Hi all,

just tried several combinations with a new PC and SSD, latest Win10.
Installed WIN10 from USB, then diskcryptor, encrypted system drive and after restart and passwort prompt, win10 repair pops up, and tells me unable to repair.
Tried several settings, incl. disabling fast start in BIOS and WIN10, no change in behaviour.
Any ideas?

Regards,
Daniel

**Comment by DavidXanatos** [comment]
sounds like your system does not boot the DC bootloader, ensure its installed to the boot drive and if its set up to be booted from in your firmware

**Comment by Mrcardude1** [comment]
Hi,
Sorry I'm a noob an have this exact same issue.

My laptop is also showing blue screen and telling me to repair, 
Please I just want my data back, I can pay you for this.

How do I install the bootloader to the drive and how do I set it to boot from firmware?

Can you please help me

**Comment by DavidXanatos** [comment]
create a live windows 10/11 boot drive using rufus.is install DC within and then you can install the missing bootloader.
Also with build 1.3.0 such issues should not be possible as the driver now requires botoloader verification before starting encryption on the OS partition
