### ISSUE TITLE
On Windows 10 (GPT, EFI) DiskCryptor does not look for a keyfile on a connected USB flash drive!

### ISSUE THREAD

**Issue by kropotin** [DavidXanatos/DiskCryptor#23]

**Comment by DavidXanatos** [comment]
do you mean during boot?

**Comment by kropotin** [comment]
Yes!.
The part is encrypted using a password and keyfile.
In the bootloader configuration, the authentication type is set - password and bootauth keyfile.
The keyfile is located on a USB flash drive that is connected.
When entering the password, the password is invalid (although the password is correct).
If the keyfile is embedded into the bootloader, everything works. But I want to take the key to an external drive.

**Comment by kropotin** [comment]
And further. In the EFI mode, the options of the boot method (active partition, first partition with appropriate password, specified partition and etc) do not seem to work. Loading in any case occurs from the efi-part according to the Windows boot manager. Choose what can be booted only via config of bcd. But I would like to boot the OS directly depending on the authentication result.
Parts:
1 - EFI
2 - unencrypted part with OS Windows.
3 - encrypted part with OS Windows.
I can’t do anything without using the OS list configured in the bсd to start the OS I need (the default one is always loaded - unencrypted).

**Comment by kropotin** [comment]
> Yes!.
> The part is encrypted using a password and keyfile.
> In the bootloader configuration, the authentication type is set - password and bootauth keyfile.
> The keyfile is located on a USB flash drive that is connected.
> When entering the password, the password is invalid (although the password is correct).
> If the keyfile is embedded into the bootloader, everything works. But I want to take the key to an external drive.

Understood.
1. Installed the bootloader on the USB flash drive.
2. Embed a keyfile.
3. Replaced the bootloader EFI\Boot\BOOTx64.efi by EFI\DCS\DcsBoot.efi (To prevent the boot menu from appearing).
It is working!
