### ISSUE TITLE
Win10 can't boot

### ISSUE THREAD

**Issue by Itz5Y** [DavidXanatos/DiskCryptor#24]
I just run the exe file and it said something like “installation finished, please reboot” After I reboot, it is now showing that “repairing the system”. Are any solution to help me to recover to the previous state? (or at least let me use my pc)

**Comment by Itz5Y** [comment]
Forgot to mention: it showed a blue screen with the error message “inaccessible boot device” for a few seconds

**Comment by Itz5Y** [comment]
I had to reset

**Comment by sayaPintar** [comment]
is this solved?

**Comment by sayaPintar** [comment]
how you solved that?!!! same situation here :(

**Comment by Itz5Y** [comment]
> how you solved that?!!! same situation here :(

I refreshed Windows

**Comment by sayaPintar** [comment]
cant solve my issues

**Comment by sayaPintar** [comment]
i fried to reset Windows but stuck 48%

**Comment by sayaPintar** [comment]
and I still cant boot and Repair computer cant help
