### ISSUE TITLE
Any plans on adding Linux support?

### ISSUE THREAD

**Issue by YyYy-YyY** [DavidXanatos/DiskCryptor#28]
dm-crypt and LUKS have terrible performance for fast SSDs, this would be a great contribution to linux...

**Comment by hardhub** [comment]
Not so terrible as VeraCrypt, but worse than DiskCryptor yes.

**Comment by YyYy-YyY** [comment]
> 
> 
> Not so terrible as VeraCrypt, but worse than DiskCryptor yes.

My experience on benchmarks are quite similar

**Comment by DavidXanatos** [comment]
I'm not using Linux enough to care for the performance of the built in encryption solutions.
Also if I would want to contribute to that part of linux I woudl look into how to increase the performance of the existing tools instead of implementing something new

**Comment by hardhub** [comment]
@DavidXanatos 

Read-write NTFS driver is now in Linux kernel (5.15). Is it the time to reconsider support for Linux?

It makes sense at least to open NTFS DiskCryptor volumes on dual boot machines.

How complex may be changes to make DiskCryptor cross-platform?

**Comment by hardhub** [comment]
@YyYy-YyY 

> dm-crypt and LUKS have terrible performance for fast SSDs, this would be a great contribution to linux...

I got the same experience but using 4K sector size during creation of encrypted drive helps a lot and I got mostly native speed.  
So yes LUKS needs tuning, Cloudflare pacthes (options) do no help, but 4K sectors did the trick for me.

**Comment by DavidXanatos** [comment]
> 
> 
> Read-write NTFS driver is now in Linux kernel (5.15). Is it the time to reconsider support for Linux?
> 
> It makes sense at least to open NTFS DiskCryptor volumes on dual boot machines.
> 
> How complex may be changes to make DiskCryptor cross-platform?

Well you need pretty much an entire re write, the only thing you can re use is the crypto and that's the smallest part, the most code is OS integration which is well OS specific.
