### ISSUE TITLE
BLAKE3 cryptographic hash function

### ISSUE THREAD

**Issue by liskaaaaaaaaaa** [DavidXanatos/DiskCryptor#3]
Hi DavidXanatos, 
can you add to the program BLAKE3 (2020) ?
is very interesting..

![blake](https://user-images.githubusercontent.com/57771031/80321355-c394eb80-881c-11ea-85e3-586706c20a0f.PNG)

[https://github.com/BLAKE3-team/BLAKE3](https://github.com/BLAKE3-team/BLAKE3)

**Comment by DavidXanatos** [comment]
DC uses the hash function only to derive fixed length keys from arbitrary length key material.
There is no really benefit from using a faster hash or from using a more secure hash.

**Comment by liskaaaaaaaaaa** [comment]
> DC uses the hash function only to derive fixed length keys from arbitrary length key material.
> There is no really benefit from using a faster hash or from using a more secure hash.

Thank you !  I have two questions
when will the next version DiskCryptor ? and are you planning to add new encryption algorithms ? [https://forum.diskcryptor.org/viewtopic.php?f=13&p=300&sid=c675adb270d611f9911289cf71425a8b#p300](https://forum.diskcryptor.org/viewtopic.php?f=13&p=300&sid=c675adb270d611f9911289cf71425a8b#p300)

thank you for developing the program! 
**you are loved**

**Comment by DavidXanatos** [comment]
> 
> 
> Thank you ! I have two questions
> when will the next version DiskCryptor ? and are you planning to add new encryption algorithms ? https://forum.diskcryptor.org/viewtopic.php?f=13&p=300&sid=c675adb270d611f9911289cf71425a8b#p300
> 
> thank you for developing the program!
> **you are loved**

there will be a beta 3 release soon, here is the preliminary changelog:

[??.04.2020] - 1.2.2/848.118.202
  [+] Add compatibility with Windows 10 feature upgrade procedure using ReflectDrivers mechanism
  [*] Improved UEFI loader CLI password entry
  [*] Restructured bootloader config GUI
  [+] Added additional EFI loader messages to the UI
  [+] Added option to enable EFI picture password from UI
  [+] Added remaining message charakters display


About new encryption algorithms after the tool is out of beta I can look into expanding its port folio of algorithms.

**Comment by DavidXanatos** [comment]
I uploaded the beta 3 now :D 
https://github.com/diskcryptor/DiskCryptor/releases/tag/v1.2.3

**Comment by liskaaaaaaaaaa** [comment]
> I uploaded the beta 3 now :D
> https://github.com/diskcryptor/DiskCryptor/releases/tag/v1.2.3

Nice :D I'm going to test :)
I hope you don't work for the NSA ;p
