### ISSUE TITLE
Error occured when installing driver (error code: 2)

### ISSUE THREAD

**Issue by Rooby69** [DavidXanatos/DiskCryptor#30]
Hi

I could not install the latest beta version on Win10
Any idea?
Will DiskCryptor be further developed? There were no updates since one year.

**Comment by Rooby69** [comment]
I have managed to get it running by manually installing the driver right click on dcrypt.inf and install. But nevertheless it would be interesting why it fails by the installer on my PC.

**Comment by sergeyganago** [comment]
I had same error, and it's gone after I enabled hardware CPU virtualization in bios.

**Comment by freempi** [comment]
I have a similar problem than you (error code 2). I downloaded diskcrypto-master.zip and right clicked on bartpe/dcrypt.inf to select "install", but when I do it I have an error message telling me that this INF file doesn't support this installation method.

Could you tell me how you managed to install it?

Thanks a lot.
