### ISSUE TITLE
Add support for different passwords per encryption

### ISSUE THREAD

**Issue by deejam** [DavidXanatos/DiskCryptor#32]
I see no benefit of encrypting more than one time if the password for each encryption are the same.

If more than one encryption are supported with the same or different algorithms but with separate passwords, it would be impossible to identify if any of the passwords are guessed correct. If the passwords are the same, guessing if it is correct is trivial by testing the password against the supported combination of algorithms.

Supporting different passwords would open up the option of encrypting multiple times with the same algorithm. This could have performance benefits since algorithms with hardware acceleration could be used, for example AES+AES with two different passwords. Guessing the first password correct would only result in random data, making it impossible to know that the password was actually correct.

**Comment by DavidXanatos** [comment]
How would that be functionaly different than just typing booth passwords into the same entry window one after an other.
From the standpoint of entropy and key length thats IMHO equivalent.
Well unless every password has more than 256 bits of entropy what i would doubt, if it woudl have you wouldn'T worry about guessing it
