### ISSUE TITLE
DiskCryptor freezing upon opening

### ISSUE THREAD

**Issue by dab1989** [DavidXanatos/DiskCryptor#33]
Hello,

I have an external hard drive that I used DiskCryptor to encrypt. Starting this past weekend when I plug in my external drive and boot up the program, DiskCryptor freezes and I can't access my external drive. Is this a program issue or a hard drive issue?

**Comment by DavidXanatos** [comment]
To me it sounds liek a harddrive issue
try an otehr PC without DC if you can see the partitions on that drive in windows disk management
