### ISSUE TITLE
Hello,I can't boot now

### ISSUE THREAD

**Issue by dllmspk76** [DavidXanatos/DiskCryptor#35]
When I encrypt C drive, i chosen"Use External Bootloader",Then I cannot access Windows and blue screen.
Where can I get the Bootloader?

**Comment by matjon** [comment]
Hello,
In README.md there is:

> Option to place boot loader on external media and to authenticate using the key media.

Did the DiskCryptor installer prompt for external media while encrypting the C: drive?

Did you set your BIOS in UEFI mode? Which version of Windows is it?

Greetings,
Mateusz

**Comment by matjon** [comment]
Please see https://diskcryptor.org/console/ and there:

> Commands for operations with bootloader
> [...]
> -boot -setpar [partition root] | Installs bootloader on an external device. The command works with  USB disks. In case if device is not formatted as bootable, then the  program will offer to format it. As a parameter, the command accepts the  letter of a partition or the path to its mounting point.

There are probably GUI commands to create an external bootloader on removable media (CD or pendrive). (I'm on Linux at the moment, so cannot check now). You probably should install DiskCryptor on another Windows computer, then generate bootloader there. Of course make sure to choose the correct device to install the bootloader too.

**Comment by DavidXanatos** [comment]
DiskCryptor is _not_ noob friendly in that way, if you select external bootloader the tool assumes you know what you do and already have created one.

But don't worry, an external bootloader is generic and not customized to your setup so you can create on on any other windows PC with DC installed and use it with the PC you have encrypted to boot.

**Comment by Ryuu-Naisho** [comment]
> Hello,
> In README.md there is:
> 
> > Option to place boot loader on external media and to authenticate using the key media.
> 
> Did the DiskCryptor installer prompt for external media while encrypting the C: drive?
> 
> Did you set your BIOS in UEFI mode? Which version of Windows is it?
> 
> Greetings,
> Mateusz

The installer never prompted me anything besides restarting my pc. Afterwards, drive c was encrypted. I didn't even have a chance to choose a password. Was a private and public key created on drive C during installation. I'm assuming it's ransomware, I'm going through the code and want to give it the benefit of a doubt. 

I was using windows 10 with latest updates.

**Comment by DavidXanatos** [comment]
The normal installer does not change do any encryption, it only installs the driver, and the user must after the reboot select which drives to encrypt and where to install the bootloader
