### ISSUE TITLE
Blue screen after installing DiskCryptor 

### ISSUE THREAD

**Issue by Pacasmayoch** [DavidXanatos/DiskCryptor#40]
Hello to everyone, I have a external harddrive that I did Cryptet 5 years ago with my old Computer on windows 7 using DiskCryptor.
Now I have a new computer with Windows 10 Home 
After downloading Disk Cryptor and install the program says I have to restart the computer. 
After this the Blue screen is coming and I have to reset the computer to older time with out installing DiskCryptor. 
So that means I'm not abel to run the program on my new computer.
What's the easiest solution to get access to my Cryptet hard disk again?  
Thanks for helping me.
Kind regards Thomas

**Comment by DavidXanatos** [comment]
use a windows 7 VM with DC
or find out why it BSOD's it should be win 10 compatible on my 10 machines i dont have such problems
