### ISSUE TITLE
Crush on win10

### ISSUE THREAD

**Issue by lukas9898** [DavidXanatos/DiskCryptor#43]
Hi I gotted encrypted Disk via Disk Cryptor on win10 and today after 1 year it crushed. I am thinking if preparing UEFI USB DEVICE with bootloader could help it to boot? I wanted get it from .zip file from last beta download but I don't know hot to proceed. Could you help me and tell how to prepare UEFI usb bootloader? Thank you🥳😁
![Uploading 16332686230803455312024033735689.jpg…]()

**Comment by DavidXanatos** [comment]
You can create a uefi bootloader on a usb drinve from teh DV bootlaoder menu
