### ISSUE TITLE
Windows 11: BSOD on boot after enabling WSL

### ISSUE THREAD

**Issue by MrChick** [DavidXanatos/DiskCryptor#44]
I have a Win11 Pro with DiskCryptor installed, everything working fine so far.
At least until I try to install WSL, then I get a BSOD immediately on startup:
```
SYSTEM THREAD EXCEPTION NOT HANDLED
in dcrypt.sys
```
Tried enabling WSL a couple of times, each time the same problem.

The Windows drive is encrypted with VeraCrypt, the other HDDs are encrypted using DiskCryptor.
I tried reproducing the issue in a VM without luck, everything works fine in there.

Sadly Windows doesn't even create a minidump in this case, so I'm not really sure how to tackle this issue.
But I'd really like to fix this / help fixing it.

Update: 
the same BSOD occurs on a clean Win11 Pro setup (install Win11, immediately install DiskCryptor, enable WSL -> BSOD on boot)

**Comment by DavidXanatos** [comment]
does the crash with win 11 also happens in a clean vm?
if so i can try to reproduce and debug it

**Comment by MrChick** [comment]
Sadly I haven't been able to reproduce the BSOD in a vm in any way, which leads me to believe that it's clashing with a piece of hardware (or it's driver to be more precise).
I'm just at a loss at how to tackle this since there isn't even a minidump. Do you have a suggestion on what I could do to provide you with more information?

**Comment by DavidXanatos** [comment]
without a minidump the only option left is to get an otehr PC and attach a kernel debugger to the problematic pc

**Comment by darktohka** [comment]
Can reproduce. Installed DiskCryptor on Windows 11 Enterprise (22000.192), with WSL2 already installed. Computer began BSOD'ing with the same error on bootup. Unfortunately, I do not have another PC to debug with.

**Comment by MrChick** [comment]
> without a minidump the only option left is to get an otehr PC and attach a kernel debugger to the problematic pc

I have that pretty much up and running. Would you be interested in remoting into the host machine to take a look for yourself?

**Comment by trias702** [comment]
Am very curious, but do you guys see this same error when using WSL2 on Windows 10? Or does it only happen with WSL2 on Windows 11?

**Comment by DavidXanatos** [comment]
I think I have to reproduce this locally or the debuging will be a pain, i'll try that first,only if that fails i'll look into remote debugging

**Comment by MrChick** [comment]
> Am very curious, but do you guys see this same error when using WSL2 on Windows 10? Or does it only happen with WSL2 on Windows 11?

Haven't tried on 10



> I think I have to reproduce this locally or the debuging will be a pain, i'll try that first,only if that fails i'll look into remote debugging

Sure, let me know if you need access (or someone to try something out)

**Comment by MrChick** [comment]
Update: can't reproduce anymore on Win11 21H2.
