### ISSUE TITLE
Boot Failure after install - secure boot disabled

### ISSUE THREAD

**Issue by pashza** [DavidXanatos/DiskCryptor#49]
I just installed beta 3 on windows 11 (while secure boot was enabled ),
upon restart that was prompted i disabled secure boot.

I still get a BSOD with inaccessible boot device.

Any suggestions?

**Comment by vaygr** [comment]
Same on W10 Pro on ASUS PRIME Z590M-PLUS.

**Comment by DavidXanatos** [comment]
remove teh driver from the registry inspect the inf file to know what to remove.
or try disabling driver signature all together i.e. put windows in test signing mode

**Comment by Xebozone** [comment]
See my comments
https://github.com/DavidXanatos/DiskCryptor/issues/41

**Comment by DavidXanatos** [comment]
build 1.3.0 has a modern whql driver signature
