### ISSUE TITLE
Encrypting system drive and another internal drive with same password prevents booting

### ISSUE THREAD

**Issue by YyYy-YyY** [DavidXanatos/DiskCryptor#5]
Any way to get this working? If I remember correctly it worked fine on the original discryptor and both drives would be mounted after Windows booted.
I thought it wasn't working because the additional drive had a MBR table, but even after modifying it to GPT it still just hangs at the "insert password" screen. 
If I type the wrong password it still displays the "wrong password" message.

**Comment by DavidXanatos** [comment]
I use that exact configuration and it works just fine.
So the issue must be something specific to your setup.

**Comment by YyYy-YyY** [comment]
My guess is that the bootloader is trying to use the 2nd drive to boot, and since it has no OS it just hangs in there. 
The main system drive is a NVMe drive, which the system identifies as drive 1, and the another one is sata, which the systems identifies as drive 0.
Any ideas on how to solve that? I tried editing bootloader config from "Boot disk MBR" to "Specified partition" and the same thing happens.
I'm almost sure it would work if I just clone the EFI partition from one drive to other, since I've tested and that works from a thumb drive, but it'll probably incur in a slighly longer boot time because the drive is slower.

**Comment by DavidXanatos** [comment]
The EFI boot loader should try to boot the OS from the same drive the bootloader is installed on, its strange that this does not work as expected.

Can you access the efi partition using a windows 2go or linux and edit the \\EFI\\DCS\\DcsProp file change VerboseDebug from 0 to 1 this will give you a lot of debug output during boot that should narrow in the issue.

Another option would be to preset the boot partition ID in the DcsProp file, this can be done from the DC GUI, for example if you have a windows 2go drive with DC installed you can boot from it mount your partitions using DC and than edit the bootlaoder settings from the UI.

**Comment by YyYy-YyY** [comment]
Thanks for the fast replies but I'll do this some other time, every time this problem happens the only way I had to solve it is to open my laptop, remove the HDD, boot from the SSD, change the password and then put the HDD back in. I don't have an USB drive fast enough for Windows2Go, I made one in the past and after 30 minutes it still wouldn't boot.
And I tried the idea of cloning the EFI partition to the 2nd disk, it still won't boot.

**Comment by DavidXanatos** [comment]
Ok, well I would like to understand the issue and fix it for others that may encounter it.
So please keep me in the loop.

UEFI is very much a hit and miss thing, for example on one of my older laptops (I keep all my old once) when CMS is enabled and I boot from a EFI USB Stick the HDD is not available at all in UEFI only when CMS is off or when booting from the HDD itself. So there may be any number of strange things happening.

About Win2Go don't really use a USB Stick, use a USB HDD that works much better, or a normal HDD with a USB adapter (cheapest option).

Or even better what I did on my laptop is to have a Win2go on an own partition on the second SSD so whenever I'm some ware wherever I can boot to Win2go just by changing the boot device in the firmware or using the UEFI built in boot menu.

btw: the VerboseDebug can be set in the GUI on the last page of the bootloader options.
