### ISSUE TITLE
Wrong estimated time displayed

### ISSUE THREAD

**Issue by ghost** [DavidXanatos/DiskCryptor#54]
If estimated time of encryption is greater than 24 hours then it does not show days or total hours.  
As solution it can show for example 28 hrs XX minutes or 1 day 4 hrs XX minutes.  

It is actual for very big HDD arrays.  
DiskCryptor cannot work without initial setup like LUKS does.

**Comment by DavidXanatos** [comment]
its just an estimate being of is acceptable
