### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by Mrcardude1** [DavidXanatos/DiskCryptor#55]
Hello there people of the internet.

I stumbled upon this amazing software and decided to try it.
Unfortunately I did not research properly and managed to mess up.

I encrypted my whole c: drive but forgot to encrypt the boot portions.

Now when I login, my laptop (razer blade 15 with a nvme storage running Windows 11) goes straight to Automatic repair and trys to repair and fails with error.
F:\Recovery\WindowsRE\Winre.wim\System32\Logfiles\Srt\SrtTrail.txt

I created a loader iso config but left it on the encrypted C: drive like an idiot.

I have tried to disable secure boot but it doesn't help

Can someone please help me?

**Comment by DavidXanatos** [comment]
If you only used a password and no key file, you can boot from an external windows 10 or 11 to go disk, as can be created with rufus and decrypt your c drive.

**Comment by Mrcardude1** [comment]
> 

I have made a fresh install of windows 11 on the usb stick and installed DC on there.
The encrypted drive is recognised but will not mount despite entering the correct password.

Any advice?

I could send screenshots or you can check via TeamViewer?
I can pay if you can check it please?

I haven't done a fresh install just yet, but will be doing it soon if data cannot be recovered

**Comment by DavidXanatos** [comment]
we can try team viewer you can find my email address in my github profile send me the id number and pw for access than i'll take a look

**Comment by Mrcardude1** [comment]
> we can try team viewer you can find my email address in my github profile send me the id number and pw for access than i'll take a look

Much appreciated.
I will set it up. I am just out at the moment and will email you the details when I am ready

Thank you again

**Comment by Mrcardude1** [comment]
Hi David,
I have sent you the email with login details
