### ISSUE TITLE
DO NOT DOWNLOAD THIS ON WINDOWS 11

### ISSUE THREAD

**Issue by Mrcardude1** [DavidXanatos/DiskCryptor#56]
As the title says, do NOT download this on windows 11.
I just lost all my data.

All I did was install DiskCryptor, reboot, encrypt C: drive and restart.
Then bam! Blue screen telling me windows isn't installed and to do a repair.

The disk started showing it had no data on it so had to do a full fresh windows without any of my data

**Comment by DavidXanatos** [comment]
You could have booted from a external windows 10 USB HDD and decrypted drive C

This tool is not for beginners, and the download page clearly says:

- This is a beta build so keep a backup and a Windows 2 Go drive on hand just in case.

Tests in a windows 11 VM showed that its still compatible and working fine.

**Comment by Mrcardude1** [comment]
I have made a fresh install of windows 11 on the usb stick and installed DC on there.
The encrypted drive is recognised but will not mount despite entering the correct password.

Any advice?

I could send screenshots or you can check via TeamViewer?
I can pay if you can check it please?

I haven't done a fresh install just yet, but will be doing it soon if data cannot be recovered
