### ISSUE TITLE
Install Bootloader

### ISSUE THREAD

**Issue by VanFlusen** [DavidXanatos/DiskCryptor#58]
If I select Install Loader under Bootloader config and answer the warning '' Do you want to add a DCS loader boot menu entry (recommended)'' with No, the bootloader is installed anyway.

![1](https://user-images.githubusercontent.com/82698833/171877352-dc4020dd-6f1e-45eb-91fc-b48312ac1f67.png)
![2](https://user-images.githubusercontent.com/82698833/171876932-7b1db63a-6ef3-417d-8a4c-56ed23c77ba0.png)
![3](https://user-images.githubusercontent.com/82698833/171877654-772455ef-c789-4ef7-8a9f-f1ed867b8388.png)

**Comment by DavidXanatos** [comment]
Yes this is intended and a different thing, adding the DCS entry means to add it to the UEFI configuration to be offered in the boot menu independent from the physical Drive.

**Comment by hardhub** [comment]
> Yes this is intended and a different thing, adding the DCS entry means to add it to the UEFI configuration to be offered in the boot menu independent from the physical Drive.

@DavidXanatos How to add this DCS entry once again to UEFI after BIOS updates? 

I cannot login to system and use DC due to encryption and missing boot entry.  
Is it possible to do all with instance of DC not installed in target system, for example using it in Windows PE?
