### ISSUE TITLE
Backup header before encryption is complete

### ISSUE THREAD

**Issue by Equim-chan** [DavidXanatos/DiskCryptor#60]
I've noticed that the backup header option isn't available until the encryption is finished, which I think could be because `tmp_size` changes during encryption. But I think it should be allowed to backup headers if the process is paused?

**Comment by DavidXanatos** [comment]
no because if you would restore such a header after it was unpaused it would screw up the difference

**Comment by Equim-chan** [comment]
Yes that's what I meant, but if I understand how it works and the risks am I able to do this?

**Comment by DavidXanatos** [comment]
i think most users won't understand and get themselves in trouble.
you can use WinHex or some other raw disk editor to backup the headers manually

**Comment by Equim-chan** [comment]
I see, thanks.
