### ISSUE TITLE
BSOD with Windows 11 22H2

### ISSUE THREAD

**Issue by zxc3033** [DavidXanatos/DiskCryptor#62]
Is Diskcryptor compatible with Windows 11 22H2? After installing Diskcryptor I get a BSOD during boot with dcrypt.sys being the problem. With Windows 11 21H2 it worked perfectly.

**Comment by DavidXanatos** [comment]
For me it woks fine but perhaps some windows settings are different

**Comment by zxc3033** [comment]
Thanks for your answer. I played with some settings and found a work around: Core Isolation in Device Security needs to be turned off.

**Comment by max403** [comment]
Hi, 
I have same error with 2 differents PC. SYSTEM THREAD EXCEPTION NOT HANDLED with dcrypt.sys
Core Isolation is already turned off.
I not found any error on events viewer

With Windows 11 21H2 it worked perfectly on this 2 machine.
I would like to help you find the cause, what would you need?

**Comment by zxc3033** [comment]
Any news in the meantime? I just installed the latest updates for Win 11 22H2 and the BSOD is back. Same problem as before with dcrypt.sys during boot. Core Isolation is off. The BSOD happens also without encrypting the partition, just by loading the driver.

A parallel installation of Win 10 on the same hardware runs without problems. Latest updates for Win 10 installed fine.

**Comment by systracer** [comment]
You need to disable Secure Boot **before** installing the driver.

**Comment by DavidXanatos** [comment]
try build 1.3.0
