### ISSUE TITLE
ERROR MOUNT VOLUME (F:) ERROR CODE: 4 

### ISSUE THREAD

**Issue by bush84** [DavidXanatos/DiskCryptor#65]
i have reviewed your website and it states if you have error 4 then the password is incorrect. 

i assure you i have the password saved in my mind and also in another password saver. 

i don't know why its not working.

please help i have all my important files on that drive. 
![Screenshot 2022-12-26 160732](https://user-images.githubusercontent.com/121439988/209552307-7ae943c8-3d95-456e-9af2-d809d593af8b.jpg)

![image](https://user-images.githubusercontent.com/121439988/209552183-9992e6af-0380-4569-be4d-75d056753d0d.png)

**Comment by DavidXanatos** [comment]
Do you have a header backup?

**Comment by luckyBlack112** [comment]
I have a similar situation. I have an older copy of this VM. Is it possible to decrypt it?
