### ISSUE TITLE
BSOD after installing on win 11 home

### ISSUE THREAD

**Issue by Apheli0n** [DavidXanatos/DiskCryptor#68]
Hi all, just downloaded diskcryptor on my windows 11 home system to use as replacement for BitLocker, Installed the program and it prompted me to restart the PC, which I did. Now it won't boot... I didn't even encrypt a drive yet so I am not sure why just installing the software gives me BSOD? Any help would be appreciated

**Comment by DavidXanatos** [comment]
DC installs a filter driver for the HDD when you windows does not like it this can result in a bsod, 
you can load the system hive from a recovery environment and remove references to DC in the filter drvier config

HKLM, SYSTEM\CurrentControlSet\Control\Class\{71A27CDD-812A-11D0-BEC7-08002BE2092F}, LowerFilters, 0x00010008, dcrypt

HKLM, SYSTEM\CurrentControlSet\Control\Class\{4D36E965-E325-11CE-BFC1-08002BE10318}, UpperFilters, 0x00010008, dcrypt

**Comment by DavidXanatos** [comment]
You can follow this simple guide to resolve the issue: https://github.com/DavidXanatos/DiskCryptor/issues/70
