### ISSUE TITLE
VirtualBox windows 10

### ISSUE THREAD

**Issue by tomaskanevicius** [DavidXanatos/DiskCryptor#71]
Hello,

I tried to run this tool on a virtual machine "Virtual box windows 10" . After disk encryption, after rebooting the machine and entering the password, windows starts but crashes and asks me to enter the password again. Secure-boot and TMP are disabled.
Do you know the reason for this?

**Comment by DavidXanatos** [comment]
try build 1.3.0 msft increased driver signing requirements in later builds of windows and 1.2.3 did not met those
