### ISSUE TITLE
Major Keyfile issue - is it true?

### ISSUE THREAD

**Issue by GY8VSdYYzvL8-K6T** [DavidXanatos/DiskCryptor#75]
Lifewire reports a massive DiskCriptor bug, but is it true? It basically says that keyfile cannot be applied to boot/system partition - https://www.lifewire.com/diskcryptor-review-2619178 

> Selecting a keyfile on this screen will make it impossible to boot back into Windows! Whether you do or don't enter a password on this screen, if you add a keyfile, you will NOT be able to log back into Windows. If you were to select a keyfile, DiskCryptor would seemingly ignore your decision during boot up by not asking for it, which results in a failed authentication, which in turn means you can't proceed past the password checkpoint.

**Comment by DavidXanatos** [comment]
You can configure the UEFI bootloader to load a key file from the volume it is on configuring the KeyFilePath entry in the config file but this is not done autoamtically. 
So yea when encrypting a boot volume this option should be grayed out.

**Comment by DavidXanatos** [comment]
build 1.3.0 now verifies if the decryption works on a test reboot with a test file before touching the system volume
