### ISSUE TITLE
Does password change invalidate header backups?

### ISSUE THREAD

**Issue by GY8VSdYYzvL8-K6T** [DavidXanatos/DiskCryptor#79]
If threat actor acquires original/initial disk header backups and password, is it enough to change just the password to invalidate original/initial header backups? Or is it necessary to re-encrypt disks with new password?

**Comment by DavidXanatos** [comment]
It is nececery to re-rncrypt all disks

Am Fr., 21. Juli 2023 um 23:10 Uhr schrieb GY8VSdYYzvL8-K6T <
***@***.***>:
