### ISSUE TITLE
Windows 11 with Core isolation disabled: "diagnosing your PC" bootloop

### ISSUE THREAD

**Issue by alejandro-amo** [DavidXanatos/DiskCryptor#80]
Just to report my personal experience:
- Recent, pretty clean Windows 11 installation in new Intel NUC PC.
- Core isolation is already disabled because of other software needing it. Double checked before installing diskcryptor anyway.
- After installation, system bootloops with "diagnosing your PC" message first and "can't boot Windows" message after that. 
- After that I only can push "reboot" or "advanced options".
- I figured out that driver was causing problems with driver signature enforcement, so I tried booting disabling that enforcement. System booted correctly, and I uninstalled the program.

**Comment by DavidXanatos** [comment]
This is to be expected, there will soon be build 1.3 out and it should get a driver signed for modern windows versions.

**Comment by alejandro-amo** [comment]
My apologies, as per reading your readme,

> We have updated DiskCryptor for use with windows 10 and 11,

My understanding led me to believe that this software was able to run properly (with no hacks, I mean) in a Windows 11 computer.

If that's not the case, I'd kinly suggest to clearly state that in readme until you are able to provide a signed driver.

**Comment by DavidXanatos** [comment]
build 1.3.0 is out https://github.com/DavidXanatos/DiskCryptor/releases/tag/v1.3.0
