### ISSUE TITLE
Can DiskCryptor mitigate cold boot attacks?

### ISSUE THREAD

**Issue by GY8VSdYYzvL8-K6T** [DavidXanatos/DiskCryptor#81]
Can it? If DiskCryptor stores passwords in clear text format in RAM when encrypted volume is mounted, then password extraction via cold boot is possible. Are there plans to introduce RAM encryption in DiskCryptor? VeraCrypt already does that.

**Comment by hardhub** [comment]
> Can it? If DiskCryptor stores passwords in clear text format in RAM when encrypted volume is mounted, then password extraction via cold boot is possible. Are there plans to introduce RAM encryption in DiskCryptor? VeraCrypt already does that.

If it is not in clear text then it is still possible. Because key for decryption will still be stored in the RAM.

There are not much places where it can be placed - CPU registers (needs kernel patches), TPM (does not make sense).

So if you worry about cold boot attacks - buy AMD and enable TME.
