### ISSUE TITLE
Virustotal results

### ISSUE THREAD

**Issue by papiru5** [DavidXanatos/DiskCryptor#84]
At VT new version has 32/72 score with most common AV brands like MS, Symantec, Kaspersky, McAfee and so on, so installation is about question. Do you plan to sign executable and fit AV tests?
![изображение](https://github.com/DavidXanatos/DiskCryptor/assets/147839328/8616a63b-461d-4b59-875c-d44d02be0d8b)

**Comment by DavidXanatos** [comment]
Nope, just complain with the AV vendor of your choice to clear the false positive.

**Comment by AlxVD** [comment]
It's probably because DCryptor is used nowadays in a several ransomware campaigns nowadays.

Therefore the ability to install it "silently" may not be a good thing.

**Comment by DavidXanatos** [comment]
> It's probably because DCryptor is used in a several ransomware campaigns nowadays.
> 
> Therefore the ability to install it "silently" may not be a good thing.

You think removing silent install from the installer would help?
I can try that.

About the ransomware campaigns this is why with build 1.3.0 we added  "safe system volume encryption (botoloader is tested before anythign gets encrypted)" it only protects the system volume but most users only have one volume anyways.

**Comment by DavidXanatos** [comment]
We have digitally signed the installer so that should take care of most of the false positives: https://github.com/DavidXanatos/DiskCryptor/releases/tag/v1.3.0b
