### ISSUE TITLE
Bug (Build v1.3 Beta): A newer version of DiskCryptor is installed

### ISSUE THREAD

**Issue by RadarNyan** [DavidXanatos/DiskCryptor#86]
I've been testing with integrating the latest version of DiskCryptor driver into Windows install media (so I can encrypt before installing Windows), everything works until I tried to run the DiskCryptor installer to restore the GUI functionalities, which I was blocked by a message saying "A newer version of DiskCryptor is installed" which is absurd since this is the latest release at the moment.

I managed to work around this by removing the "sysBuild" key from the registry after locating the cause of this message [in the source code](https://github.com/DavidXanatos/DiskCryptor/blob/a5bc29b31338a0db2a5b2a5a1d5ff9d898b9c9d0/DCrypt/setup/setup.iss#L98), to be fair the driver would work without this key, so I can just exclude it when trying to integrate the driver.

You can reproduce this by just running the installer again after installation.

**Comment by DavidXanatos** [comment]
thanks for pointing that mistake out i have re uploaded the installer

**Comment by RadarNyan** [comment]
The new installer installs just fine, but it doesn't produce the "Current version of DiskCryptor is already installed." message as written in the source code. Not sure what impact does it have.
