### ISSUE TITLE
EFI bootloader crashes if a partition was formatted by DiskCryptor

### ISSUE THREAD

**Issue by fbno** [DavidXanatos/DiskCryptor#93]
How to reproduce the issue:
- Install DiskCryptor 1.3
- Encrypt system drive and install EFI bootloader
- Reboot, finish system encryption
- In DiskCryptor GUI, right click on another partition, select "Format", use same password
- Reboot, enter password
- Bootloader crashes

If I replace the file EFI\DCS\DcsInt.dcs with one that I built based on DiskCryptor 1.2.3 and my patch from pull request #20, it works fine. Are you sure that the patch is included in the DiskCryptor 1.3 binary?

**Comment by Null-Kelvin** [comment]
> If I replace the file EFI\DCS\DcsInt.dcs with one that I built based on DiskCryptor 1.2.3 and my patch from pull request #20, it works fine.
Can you upload your fix here?

**Comment by fbno** [comment]
Sure: https://github.com/fbno/DiskCryptor/blob/bootloader-patch/Patch/DiskCryptor-1.2.3-EFI-Bootloader-Patch.zip

**Comment by Null-Kelvin** [comment]
Thanks! Work like a charm.

**Comment by DavidXanatos** [comment]
I'll check why the fix is not included in the current build and upload a new release, thanks for bringing it to my atention

**Comment by DavidXanatos** [comment]
the fix should be included in the latest signed release https://github.com/DavidXanatos/DiskCryptor/releases/tag/v1.3.0b
