### ISSUE TITLE
Trojan-Ransom.Win32.Dcryptor.bb in version 3.0

### ISSUE THREAD

**Issue by BalouPalou** [DavidXanatos/DiskCryptor#97]
Hello,

Just to inform that my antivirus detects "Trojan-Ransom.Win32.Dcryptor.bb" when trying to download Diskcryptor version 1.3

Regards

**Comment by stevenforwords** [comment]
I was very interested in testing Diskcryptor and the other Xanasoft tools but when all my internet browsers tell me "Warning Virus!" and block the download, then the upload of the executable to online antivirus analysis sites indicates even worse for the original executable and the 1.3 beta. Sorry this is not serious or professional. I can't believe GitHub allows the upload of such files....
![screen_2024-01-30_00h21m05s](https://github.com/DavidXanatos/DiskCryptor/assets/158111445/e3316c03-2c97-4ddf-ac05-187a7531488a)
![screen_2024-01-30_00h20m48s](https://github.com/DavidXanatos/DiskCryptor/assets/158111445/f9df22bc-98ed-4bbf-ac77-7b7ee46a3455)

**Comment by DavidXanatos** [comment]
We have digitally signed the installer so that should take care of most of the false positives: https://github.com/DavidXanatos/DiskCryptor/releases/tag/v1.3.0b

**Comment by stevenforwords** [comment]
Great! No more alert with my Firefox browser or ESET AV! Many thanks David! I'm gonna test it.

**Comment by BalouPalou** [comment]
Thank a lot,

There is no more virus detection.

I installed it and received an error 87 message, but after the reboot everything seems to work fine.

De : DavidXanatos ***@***.***>
Envoyé : vendredi 23 février 2024 15:15
À : DavidXanatos/DiskCryptor ***@***.***>
Cc : BalouPalou ***@***.***>; Author ***@***.***>
Objet : Re: [DavidXanatos/DiskCryptor] Trojan-Ransom.Win32.Dcryptor.bb in version 3.0 (Issue #97)

We have digitally signed the installer so that should take care of most of the false positives: https://github.com/DavidXanatos/DiskCryptor/releases/tag/v1.3.0b
