### ISSUE TITLE
Trojan:Win32/Wacatac, CANNOT DOWNLOAD DISKCRYPTOR!

### ISSUE THREAD

**Issue by Naamakalu** [DavidXanatos/DiskCryptor#99]
Ok this is getting annoying, how are we supposed to try this software and possibly like it, and possibly donate / subscribe when we can't even download? No matter what I choose to do, Windows Defender insists on deleting this file. I suppose it's mistaken for some kind of ransomware virus, but there is no way to bypass this. AUTHOR, are you awake? I need something to replace BitLocker and Veracrypt wasn't it. Get this shit sorted out, I want Diskcryptor.

**Comment by Naamakalu** [comment]
![image](https://github.com/DavidXanatos/DiskCryptor/assets/159555865/78dc46a3-1153-46b6-b38d-48e3f59593a8)

**Comment by DavidXanatos** [comment]
There is ofcause a way to bypass it, just take control of your Windows Defender there are plenty GPO's you can set to take control.

**Comment by DavidXanatos** [comment]
We have digitally signed the installer so that should take care of most of the false positives: https://github.com/DavidXanatos/DiskCryptor/releases/tag/v1.3.0b
